#!/bin/bash

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

#$(ssh-agent -s)

xset +fp ~/.fonts
xset fp rehash

xrdb -merge ~/.Xresources

#exec compton -b

setxkbmap gb -option ctrl:nocaps -option terminate:ctrl_alt_bksp

xsetroot -cursor_name left_ptr
#xrandr --output eDP-1 --panning 1920x1080 --scale 1.406x1.406

exec xmonad
